### ISSUE TITLE
Republish React 15 docs

### ISSUE THREAD

**Issue by slashwhatever** [reactjs/reactjs.org#852]
Some of us still have to use React 15 while the impacts of React 16 are assessed against our Enterprise scale apps.

Please republish the last version of the React 15 docs.

**Comment by gaearon** [comment]
You can build them [from here](https://github.com/facebook/react/tree/15-stable/docs) and then publish them, or you can view them inline in the git branch I linked.

We've already started publishing [snapshots of docs per version](https://reactjs.org/versions) but we don't have one for React 15. I guess we *could* publish it though.

**Comment by gaearon** [comment]
One thing I'm worried about is that it'll start getting Google juice like a Chinese fork of React 15 docs does. And then people will find it instead of the main docs by accident.

**Comment by alexkrolick** [comment]
True... looks like React Native does this: https://github.com/facebook/react-native-website/tree/master/website/versioned_docs

Then maybe robots.txt could be told not to index certain versioned routes?

See also https://github.com/reactjs/reactjs.org/issues/85

**Comment by jaredp** [comment]
Not generally useful, but if you're on v15.4.2 I've got https://jpochtar.me/react/

**Comment by bvaughn** [comment]
Thanks Alex!

**Comment by leongaban** [comment]
Hi @gaearon I tried to rebuild it but running into this error `Error: Cannot find module 'rollup'`

Tho, for others I did find this helpful link: https://jpochtar.me/react/
Some random guy on the internet is hosting it.

**Comment by bvaughn** [comment]
@leongaban Alex's comment above points to [react-legacy.netlify.com](https://react-legacy.netlify.com/) which is also now linked to [on the React version page](https://reactjs.org/versions so I would recommend just using it.

**Comment by leongaban** [comment]
Thanks @bvaughn, I did find that link to `15.6.2` however an app I'm going to have to work on is in `15.0.2`, so the `15.4.2` version was the oldest I could find. Hopefully an upgrade to 16 will happen this year ;)

**Comment by slashwhatever** [comment]
> @leongaban Alex's comment above points to [react-legacy.netlify.com](https://react-legacy.netlify.com/) which is also now linked to [on the React version page](https://reactjs.org/versions so I would recommend just using it.

Seems that clicking a result in the search on the netlify page just routes you back to the latest v16 docs though

**Comment by alexkrolick** [comment]
> Seems that clicking a result in the search on the netlify page just routes you back to the latest v16 docs though

Correct; I believe this is an issue with all of the old versions, including the 16 & 17 release families
