### PR TITLE
Fix code examples error in useLayoutEffect and useMemo documentation

### LINKED ISSUE #8059: [Bug]: client-side exception when visiting useLayoutEffect page
### Summary

Sometime this afternoon, the page for `useLayoutEffect`:

https://react.dev/reference/react/useLayoutEffect

broke with:

> Application error: a client-side exception has occurred (see the browser console for more information).

### Page

https://react.dev/reference/react/useLayoutEffect

### Details

Console:

```
framework-76ad44d61c11f057.js:1 Error: File /src/App.js was defined multiple times. Each file snippet should have a unique path name
    at 145-0963f310eaedf893.js:1:299499
    at Array.reduce (<anonymous>)
    at n (145-0963f310eaedf893.js:1:298499)
    at 145-0963f310eaedf893.js:1:250798
    at lb (framework-76ad44d61c11f057.js:1:41610)
    at aY (framework-76ad44d61c11f057.js:1:61337)
    at aW (framework-76ad44d61c11f057.js:1:60197)
    at aB (framework-76ad44d61c11f057.js:1:59814)
    at ot (framework-76ad44d61c11f057.js:1:76212)
    at ua (framework-76ad44d61c11f057.js:1:111832)
aR @ framework-76ad44d61c11f057.js:1
main-6b2aa10951d4c273.js:1 Error: File /src/App.js was defined multiple times. Each file snippet should have a unique path name
    at 145-0963f310eaedf893.js:1:299499
    at Array.reduce (<anonymous>)
    at n (145-0963f310eaedf893.js:1:298499)
    at 145-0963f310eaedf893.js:1:250798
    at lb (framework-76ad44d61c11f057.js:1:41610)
    at aY (framework-76ad44d61c11f057.js:1:61337)
    at aW (framework-76ad44d61c11f057.js:1:60197)
    at aB (framework-76ad44d61c11f057.js:1:59814)
    at ot (framework-76ad44d61c11f057.js:1:76212)
    at ua (framework-76ad44d61c11f057.js:1:111832)
Q @ main-6b2aa10951d4c273.js:1
main-6b2aa10951d4c273.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Q @ main-6b2aa10951d4c273.js:1
```

Browser: Chromium 141, Firefox 143
OS: Linux

Possibly related to 8d73630aa5463c394d1b825d35b804a2a9e4324b (#8058). So, C/C'ing @poteto.

### PR DESCRIPTION
**Pull request by armedi**
Fixes #8059 

Not only the useLayoutEffect page as reported in the above issue, the useMemo page is also affected

### CODE REVIEW

**Comment by armedi** [comment]
Tagging @poteto as this PR fixes bug introduced in #8058

**Comment by poteto** [comment]
This was fixed in #8063
